export const types = {
    ADD: "ADD",
    CHANGE_TITLE: "CHANGE_TITLE",
    CHANGE_TITLE_WITH_PARAMS: "CHANGE_TITLE_WITH_PARAMS",
    CHANGE_INPUT_VALUE: "CHANGE_INPUT_VALUE",
    DELETE: "DELETE",
    CHANGE_NUM_ONE: "CHANGE_NUM_ONE",
    CHANGE_NUM_TWO: "CHANGE_NUM_TWO",
    MAKE_RESULT: "MAKE_RESULT",
    USERS: "USERS",
}